#!/usr/bin/env bash

## Instal ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## pull ansible
sudo ansible-ull -U https://github.com/enklein/ansible.git
## prime's contains .ssh, auth_codes, tasks, Dockerfile, ansible-run, build-dockers, clean-env, local.yml, nvim.Dockerfile