- name: shutter ppa (ppa:shutter/ppa)
  become: true
  apt_repository:
   repo: ppa:shutter/ppa
   state: present
   update_cache: True
  tags:
    - install
    - productivity

- name: Install packages
  become: true
  apt:
    name: [ "fzf", "xclip", "screenkey", "tldr", "ripgrep", "rofi" "shutter" ]
    # name: [ "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "shutter" ]
  tags:
    - install
    - productivity